/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Areas */
        get: operations["list_areas_api_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaDTO */
        AreaDTO: {
            /** Area Path */
            area_path: string;
            /** Display Name */
            display_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ResultDTO */
        ResultDTO: {
            /** Doc Id */
            doc_id: number;
            /** Titulo */
            titulo: string;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Area Path */
            area_path: string;
            /** Tipo */
            tipo: string;
            /** Abstract */
            abstract: string | null;
            /** Snippet */
            snippet: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["ResultDTO"][];
            /** Total */
            total: number;
            /** Saturated */
            saturated: boolean;
            /** Unfiltered Total */
            unfiltered_total?: number | null;
            /**
             * Lexical Fallback
             * @default false
             */
            lexical_fallback: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                pagina?: number;
                area?: string | null;
                tipo?: ("tesis" | "paper" | "trabajo_practico" | "proyecto_investigacion" | "monografia" | "ponencia_poster" | "apunte_resumen" | "informe_catedra")[];
                desde?: number | null;
                hasta?: number | null;
                orden?: "relevancia" | "recientes";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_areas_api_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaDTO"][];
                };
            };
        };
    };
}
