/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Endpoint */
        get: operations["search_endpoint_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Areas */
        get: operations["list_areas_api_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_api_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Users */
        get: operations["search_users_api_users_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread_count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Count */
        get: operations["unread_count_api_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/mark_all_read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_api_notifications_mark_all_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coauthor_invitations/{doc_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_coauthor_invitations__doc_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coauthor_invitations/{doc_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline */
        post: operations["decline_api_coauthor_invitations__doc_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft Endpoint */
        post: operations["create_draft_endpoint_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Main File */
        post: operations["upload_main_file_api_documents__doc_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace Main File */
        post: operations["replace_main_file_api_documents__doc_id__replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/candidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Discard Candidate Endpoint */
        delete: operations["discard_candidate_endpoint_api_documents__doc_id__candidate_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_documents__doc_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/coauthors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Coauthor */
        post: operations["post_coauthor_api_documents__doc_id__coauthors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/coauthors/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Coauthor */
        delete: operations["delete_coauthor_api_documents__doc_id__coauthors__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_documents__doc_id__delete"];
        options?: never;
        head?: never;
        /** Patch Draft */
        patch: operations["patch_draft_api_documents__doc_id__patch"];
        trace?: never;
    };
    "/api/documents/{doc_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Document */
        post: operations["publish_document_api_documents__doc_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Document */
        post: operations["restore_document_api_documents__doc_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Attachment */
        post: operations["post_attachment_api_documents__doc_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/attachments/{att_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Attachment */
        delete: operations["delete_attachment_api_documents__doc_id__attachments__att_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Own Documents */
        get: operations["get_own_documents_api_me_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/documents/deleted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deleted Documents */
        get: operations["get_deleted_documents_api_me_documents_deleted_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doc Detail */
        get: operations["get_doc_detail_api_docs__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{doc_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doc Related */
        get: operations["get_doc_related_api_docs__doc_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{doc_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Main File */
        get: operations["download_main_file_api_docs__doc_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{doc_id}/attachments/{att_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Attachment */
        get: operations["download_attachment_api_docs__doc_id__attachments__att_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{doc_id}/versions/{n}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Version */
        get: operations["download_version_api_docs__doc_id__versions__n__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Download Version */
        head: operations["download_version_api_docs__doc_id__versions__n__download_get"];
        patch?: never;
        trace?: never;
    };
    "/api/moderation/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_api_moderation_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue */
        get: operations["queue_api_moderation_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/reports/{report_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Document */
        get: operations["inspect_document_api_moderation_reports__report_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/reports/{report_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Download */
        get: operations["inspect_download_api_moderation_reports__report_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/reports/{report_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hide Report */
        post: operations["hide_report_api_moderation_reports__report_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/reports/{report_id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unhide Report */
        post: operations["unhide_report_api_moderation_reports__report_id__unhide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/reports/{report_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Report */
        post: operations["dismiss_report_api_moderation_reports__report_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionBody */
        ActionBody: {
            /** Reason */
            reason?: string | null;
        };
        /** AreaDTO */
        AreaDTO: {
            /** Area Path */
            area_path: string;
            /** Display Name */
            display_name: string;
        };
        /** AttachmentDTO */
        AttachmentDTO: {
            /** Id */
            id: number;
            /** Original Filename */
            original_filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Mime */
            mime: string | null;
        };
        /** AuthorDisplayDTO */
        AuthorDisplayDTO: {
            /** Display Name */
            display_name: string;
            /** User Id */
            user_id: number | null;
        };
        /** Body_post_attachment_api_documents__doc_id__attachments_post */
        Body_post_attachment_api_documents__doc_id__attachments_post: {
            /** File */
            file: string;
        };
        /** Body_replace_main_file_api_documents__doc_id__replace_post */
        Body_replace_main_file_api_documents__doc_id__replace_post: {
            /** File */
            file: string;
        };
        /** Body_upload_main_file_api_documents__doc_id__upload_post */
        Body_upload_main_file_api_documents__doc_id__upload_post: {
            /** File */
            file: string;
        };
        /** CandidateStateDTO */
        CandidateStateDTO: {
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "ready" | "failed";
            /** Staged Abstract */
            staged_abstract: string | null;
            /** Staged Keywords */
            staged_keywords: string[];
            /** Staged Fecha */
            staged_fecha: string | null;
            /** Can Publish */
            can_publish: boolean;
            /** Can Discard */
            can_discard: boolean;
            /** Indexed At */
            indexed_at: string | null;
            /** Error */
            error: string | null;
        };
        /** CoauthorRowDTO */
        CoauthorRowDTO: {
            /** User Id */
            user_id: number | null;
            /** Display Name */
            display_name: string;
            /** Email Local */
            email_local: string | null;
            /** Email */
            email: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "owner" | "pending" | "accepted" | "declined" | "external";
        };
        /** ExternalAuthorInput */
        ExternalAuthorInput: {
            /** Name */
            name: string;
            /** Surname */
            surname: string;
            /** Email */
            email: string;
        };
        /** CreateDraftRequest */
        CreateDraftRequest: {
            /** Title */
            title: string;
            /** Area Path */
            area_path: string;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "tesis" | "paper" | "trabajo_practico" | "proyecto_investigacion" | "monografia" | "ponencia_poster" | "apunte_resumen" | "informe_catedra";
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "publico" | "interno" | "privado";
            /**
             * External Authors
             * @default []
             */
            external_authors: components["schemas"]["ExternalAuthorInput"][];
            /**
             * Coauthor User Ids
             * @default []
             */
            coauthor_user_ids: number[];
        };
        /** CreateDraftResponse */
        CreateDraftResponse: {
            /** Id */
            id: number;
        };
        /** DeletedDocDTO */
        DeletedDocDTO: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Publication Status */
            publication_status: string;
            /**
             * Purge At
             * Format: date-time
             */
            purge_at: string;
        };
        /** DetailDTO */
        DetailDTO: {
            /** Doc Id */
            doc_id: number;
            /** Titulo */
            titulo: string;
            /** Autores */
            autores: components["schemas"]["AuthorDisplayDTO"][];
            /** Area Path */
            area_path: string;
            /** Tipo */
            tipo: string;
            /** Fecha */
            fecha: string | null;
            /** Visibility */
            visibility: string;
            /** Abstract */
            abstract: string;
            /** Palabras Clave */
            palabras_clave: string[];
            archivo_principal: components["schemas"]["MainFileDTO"];
            /** Adjuntos */
            adjuntos: components["schemas"]["AttachmentDTO"][];
            /** Versions */
            versions?: components["schemas"]["DetailVersionDTO"][] | null;
            /** Manageable */
            manageable: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view: "detail";
        };
        /** DetailVersionDTO */
        DetailVersionDTO: {
            /** N */
            n: number;
            /** Original Filename */
            original_filename: string;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
            /** Indexed At */
            indexed_at: string | null;
            /** Is Current */
            is_current: boolean;
        };
        /** DetailWithInvitationDTO */
        DetailWithInvitationDTO: {
            /** Doc Id */
            doc_id: number;
            /** Titulo */
            titulo: string;
            /** Autores */
            autores: components["schemas"]["AuthorDisplayDTO"][];
            /** Area Path */
            area_path: string;
            /** Tipo */
            tipo: string;
            /** Fecha */
            fecha: string | null;
            /** Visibility */
            visibility: string;
            /** Abstract */
            abstract: string;
            /** Palabras Clave */
            palabras_clave: string[];
            archivo_principal: components["schemas"]["MainFileDTO"];
            /** Adjuntos */
            adjuntos: components["schemas"]["AttachmentDTO"][];
            /** Versions */
            versions?: components["schemas"]["DetailVersionDTO"][] | null;
            /** Manageable */
            manageable: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view: "detail_with_invitation";
            invitation: components["schemas"]["InvitationBannerDTO"];
        };
        /** DraftStateDTO */
        DraftStateDTO: {
            /** Title */
            title: string;
            /** Index Status */
            index_status: string;
            /** Staged Abstract */
            staged_abstract: string | null;
            /** Staged Keywords */
            staged_keywords: string[];
            /** Staged Fecha */
            staged_fecha: string | null;
            /** Generated Abstract */
            generated_abstract: string | null;
            /** Generated Keywords */
            generated_keywords: string[];
            /** Generated Fecha */
            generated_fecha: string | null;
            /** Index Error */
            index_error: string | null;
            /** Publish Gate Reason */
            publish_gate_reason: string | null;
            /** Is Owner */
            is_owner: boolean;
            /** Visibility */
            visibility: "publico" | "interno" | "privado";
            /** Attachments */
            attachments: components["schemas"]["AttachmentDTO"][];
            /** Coauthors */
            coauthors: components["schemas"]["CoauthorRowDTO"][];
            /** Versions */
            versions: components["schemas"]["DraftVersionDTO"][];
            candidate: components["schemas"]["CandidateStateDTO"] | null;
        };
        /** DraftVersionDTO */
        DraftVersionDTO: {
            /** N */
            n: number;
            /** Original Filename */
            original_filename: string;
            /** Mime */
            mime: string;
            /** Size Bytes */
            size_bytes: number;
            /** Indexed At */
            indexed_at: string | null;
            /** Is Current */
            is_current: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HideBody */
        HideBody: {
            /** Reason */
            reason: string;
        };
        /** InspectMetadataDTO */
        InspectMetadataDTO: {
            /** Titulo */
            titulo: string;
            /** Abstract */
            abstract: string;
            /** Palabras Clave */
            palabras_clave: string[];
            /** Autores */
            autores: components["schemas"]["AuthorDisplayDTO"][];
            /** Tipo */
            tipo: string;
            /** Area Path */
            area_path: string;
        };
        /** InvitationBannerDTO */
        InvitationBannerDTO: {
            /** Inviter Display Name */
            inviter_display_name: string;
        };
        /** InviteCoauthorRequest */
        InviteCoauthorRequest: {
            /** User Id */
            user_id: number;
        };
        /** MainFileDTO */
        MainFileDTO: {
            /** Original Filename */
            original_filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Mime */
            mime: string;
        };
        /** MarkAllReadResponse */
        MarkAllReadResponse: {
            /** Count */
            count: number;
        };
        /** MarkReadResponse */
        MarkReadResponse: {
            /** Id */
            id: number;
            /**
             * Read At
             * Format: date-time
             */
            read_at: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "estudiante" | "docente";
            /** Name */
            name: string;
            /** Picture Url */
            picture_url: string | null;
            /** Hd */
            hd: string;
        };
        /** MinimalInviteDTO */
        MinimalInviteDTO: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            view: "minimal";
            /** Doc Id */
            doc_id: number;
            /** Titulo */
            titulo: string;
            /** Inviter Display Name */
            inviter_display_name: string;
        };
        /** NotificationDTO */
        NotificationDTO: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Read At */
            read_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NotificationsResponse */
        NotificationsResponse: {
            /** Items */
            items: components["schemas"]["NotificationDTO"][];
        };
        /** OwnDocDTO */
        OwnDocDTO: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Publication Status */
            publication_status: string;
            /** Visibility */
            visibility: string;
            /** Published At */
            published_at: string | null;
        };
        /** QueueEntryDTO */
        QueueEntryDTO: {
            /** Doc Id */
            doc_id: number;
            /** Report Id */
            report_id: number;
            /** Title */
            title: string;
            /** Reasons */
            reasons: string[];
            /**
             * First Reported At
             * Format: date-time
             */
            first_reported_at: string;
            /**
             * Last Reported At
             * Format: date-time
             */
            last_reported_at: string;
            /** Report Count */
            report_count: number;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Items */
            items: components["schemas"]["QueueEntryDTO"][];
        };
        /** RelatedDTO */
        RelatedDTO: {
            /** Doc Id */
            doc_id: number;
            /** Titulo */
            titulo: string;
            /** Autores */
            autores: components["schemas"]["AuthorDisplayDTO"][];
            /** Area Path */
            area_path: string;
            /** Tipo */
            tipo: string;
            /** Fecha */
            fecha: string | null;
        };
        /** ReportBody */
        ReportBody: {
            /** Doc Id */
            doc_id: number;
            /**
             * Reason
             * @enum {string}
             */
            reason: "spam" | "contenido_inadecuado" | "plagio" | "error";
        };
        /** ResultDTO */
        ResultDTO: {
            /** Doc Id */
            doc_id: number;
            /** Titulo */
            titulo: string;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Area Path */
            area_path: string;
            /** Tipo */
            tipo: string;
            /** Abstract */
            abstract: string | null;
            /** Snippet */
            snippet: string;
            /** Snippet Is Html */
            snippet_is_html: boolean;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "publico" | "interno" | "privado";
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["ResultDTO"][];
            /** Total */
            total: number;
            /** Saturated */
            saturated: boolean;
            /** Unfiltered Total */
            unfiltered_total?: number | null;
            /**
             * Lexical Fallback
             * @default false
             */
            lexical_fallback: boolean;
        };
        /** UnreadCountResponse */
        UnreadCountResponse: {
            /** Count */
            count: number;
        };
        /** UpdateDraftRequest */
        UpdateDraftRequest: {
            /** Title */
            title?: string | null;
            /** Abstract */
            abstract?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Fecha */
            fecha?: string | null;
            /** Visibility */
            visibility?: ("publico" | "interno" | "privado") | null;
            /** Area Path */
            area_path?: string | null;
            /** Document Type */
            document_type?: ("tesis" | "paper" | "trabajo_practico" | "proyecto_investigacion" | "monografia" | "ponencia_poster" | "apunte_resumen" | "informe_catedra") | null;
        };
        /** UserSearchResult */
        UserSearchResult: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Email Local */
            email_local: string;
            /** Picture Url */
            picture_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_endpoint_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                pagina?: number;
                area?: string | null;
                tipo?: ("tesis" | "paper" | "trabajo_practico" | "proyecto_investigacion" | "monografia" | "ponencia_poster" | "apunte_resumen" | "informe_catedra")[];
                desde?: number | null;
                hasta?: number | null;
                orden?: "relevancia" | "recientes";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_areas_api_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaDTO"][];
                };
            };
        };
    };
    login_api_auth_login_get: {
        parameters: {
            query?: {
                next?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    google_callback_api_auth_google_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_users_api_users_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsResponse"];
                };
            };
        };
    };
    unread_count_api_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountResponse"];
                };
            };
        };
    };
    mark_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_api_notifications_mark_all_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkAllReadResponse"];
                };
            };
        };
    };
    accept_api_coauthor_invitations__doc_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_api_coauthor_invitations__doc_id__decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_endpoint_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_main_file_api_documents__doc_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_main_file_api_documents__doc_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_main_file_api_documents__doc_id__replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_main_file_api_documents__doc_id__replace_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_candidate_endpoint_api_documents__doc_id__candidate_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_documents__doc_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftStateDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_coauthor_api_documents__doc_id__coauthors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCoauthorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_coauthor_api_documents__doc_id__coauthors__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_draft_api_documents__doc_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_document_api_documents__doc_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_document_api_documents__doc_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_attachment_api_documents__doc_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_attachment_api_documents__doc_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attachment_api_documents__doc_id__attachments__att_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
                att_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_own_documents_api_me_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnDocDTO"][];
                };
            };
        };
    };
    get_deleted_documents_api_me_documents_deleted_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedDocDTO"][];
                };
            };
        };
    };
    get_doc_detail_api_docs__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailDTO"] | components["schemas"]["MinimalInviteDTO"] | components["schemas"]["DetailWithInvitationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doc_related_api_docs__doc_id__related_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_main_file_api_docs__doc_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_attachment_api_docs__doc_id__attachments__att_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
                att_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_version_api_docs__doc_id__versions__n__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
                n: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_version_api_docs__doc_id__versions__n__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
                n: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_moderation_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_api_moderation_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
        };
    };
    inspect_document_api_moderation_reports__report_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectMetadataDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_download_api_moderation_reports__report_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_report_api_moderation_reports__report_id__hide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HideBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unhide_report_api_moderation_reports__report_id__unhide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_report_api_moderation_reports__report_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
